# Generated by Django 4.1.4 on 2022-12-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('queue', models.TextField()),
                ('name', models.TextField()),
                ('props', models.JSONField()),
                ('error', models.TextField(blank=True, null=True)),
                ('retry_num', models.SmallIntegerField()),
                ('max_retries', models.SmallIntegerField()),
                ('status', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False, 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectprofilerel',
            options={'managed': False, 'verbose_name': 'Project && Profile', 'verbose_name_plural': 'Projects && Profiles'},
        ),
        migrations.AlterModelOptions(
            name='storageobject',
            options={'managed': False, 'verbose_name': 'Storage Object', 'verbose_name_plural': 'Storage Objects'},
        ),
        migrations.AlterModelOptions(
            name='teamprofilerel',
            options={'managed': False, 'verbose_name': 'Team && Profile', 'verbose_name_plural': 'Teams && Profiles'},
        ),
    ]
