# Generated by Django 4.1.4 on 2022-12-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penpot', '0003_file_filechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uri', models.TextField()),
                ('mtype', models.TextField()),
                ('error_code', models.TextField(blank=True, null=True)),
                ('error_count', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='teamprojectprofilerel',
            options={'managed': False, 'verbose_name': 'Teams && Projects & Profiles'},
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('webhook', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='penpot.webhook')),
                ('created_at', models.DateTimeField()),
                ('error_code', models.TextField(blank=True, null=True)),
                ('req_data', models.JSONField(blank=True, null=True)),
                ('rsp_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_delivery',
                'managed': False,
            },
        ),
    ]
