# Generated by Django 4.1.4 on 2022-12-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penpot', '0005_auditlog_comment_commentthread_filemediaobject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectprofilerel',
            options={'managed': False, 'verbose_name': 'Project Member', 'verbose_name_plural': 'Project Members'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False, 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamprofilerel',
            options={'managed': False, 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'managed': False, 'verbose_name': 'Webhook Delivery', 'verbose_name_plural': 'Webhook Deliveries'},
        ),
    ]
